### PR TITLE
New logo

### LINKED ISSUE #135: Need new logo
Project needs a logo.
images/logo.png needs to be changed to "hapijs university"  from "hueniversity".
Be creative but keep the hapijs space cadet hat in the logo.

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
Closes #135

### CODE REVIEW

**Comment by FennNaten** [comment]
Great :)

**Comment by AdriVanHoudt** [comment]
Thanks, I used all my "pro GIMP skills" for this haha

**Comment by zoe-1** [comment]
@AdriVanHoudt  Nice Job :-)

**Comment by idanwe** [comment]
The hapijs in the logo should be lower case

**Comment by AdriVanHoudt** [comment]
It is only the 'H' is uppercase, the font is just super bold

**Comment by idanwe** [comment]
Yeah, I noticed. But, hapi should always be lower case according to @hueniverse

**Comment by AdriVanHoudt** [comment]
Ah like that, I'll look into it tomorrow

**Comment by AdriVanHoudt** [comment]
Ok setting the H to lowercase doesn't look as good, maybe use the original hapi logo with 'University' after it?

**Comment by idanwe** [comment]
I think it is good idea

**Pull request merged**
