### PR TITLE
Assignment5

### PR DESCRIPTION
**Pull request by rutaihwa**
Assignement5, late submission :neutral_face: 
#136

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
LGTM, why is travis not running for this?

**Comment by zoe-1** [comment]
@AdriVanHoudt checking on it.

**Comment by zoe-1** [comment]
@AdriVanHoudt 
See my last comment this post https://github.com/hapijs/university/issues/143 .
I think that issue may relate to this one.

**Comment by zoe-1** [comment]
@AdriVanHoudt It's OK now. @nlf fixed the hapijs/university travis issue. 
Just a restart that was needed.  So, that fixes the university repo travis issue. 
I think @rutaihwa should trigger travis to re-run. His project should pass travis now.

**Comment by rutaihwa** [comment]
Thanks @AdriVanHoudt and @zoe-1 , I have tried to restart travis and test runs but fails, that expected right?

**Comment by zoe-1** [comment]
@rutaihwa  your project OK with travis. Since this is assignment5 and we moved on to assignment6. 
You are behind the head on the master branch.  So, travis will not pass telling us there are merge conflicts.  This means if we did want to merge your PR into master it would require us to resolve conflicts first. 

We have already merged in the PR for assignment5 and moved on to assignment6 
so please do not worry about this not passing. Have fun coding!

**Comment by rutaihwa** [comment]
Thanks @zoe-1 ! :+1:

**Pull request closed without merging**
