### PR TITLE
Assignment: glue and html views (hapijs/university#136)

### LINKED ISSUE #136: Glue and HTML views
#### We transitioned to hapijs university.

For details about this change see: <br/>
* New [README](https://github.com/hapijs/university) for explanation of changes.
* [This Discussion] (https://github.com/hapijs/university/issues/132). To see current thoughts about project direction.
* And this [Documentation](https://github.com/hapijs/university/issues/133)

Let's keep our project going! This is community learning which means much of the learning will be 
horizontal and not just vertical! Make your contribution, ask questions, give advice (review others code) , share your thoughts about our project's direction and let's push each other to keep growing :-) 

## The Assignment

*  Refactor the application to use the hapijs server composer  [hapijs / glue](https://github.com/hapijs/glue).  <br/>Glue should be used to load "version" and "private" plugins.
Here is a helpful resource from the Glue project: [Sample Manifest JSON object](https://github.com/hapijs/glue/blob/master/lib/index.js) . 

*  Create a plugin called "home":
   * This plugin should contain one endpoint called "home".
   * Configure the plugin to use handlebars template rendering engine to render html templates.
   * Configure this plugin to serve html view files and make the home endpoint render an html page/template named home.
   *  Configure the home plugin to find view files in a directory named "views" located in
   the root path of the application. For now, just make html pages for view files (no .hbs files).
 * The view directory should contain one html template named home.html. <br/>
    When viewed in a browser, the home.html template should display the path to this view file from the root of our project. 
*  In the end, the application should have thee endpoints. One called: "home", 
   the other called "version", and one called "private". Each point is located in it's own plugin 
   which glue composes when the server starts up. 
*  Ensure 100% test coverage.
*  Refactor project to meet new requirements https://github.com/hapijs/contrib/issues/31.  
   - Remove Makefile and switch to using npm scripts (see hapi package.json)
   - Remove root index.js (point package.json to lib/index.js)
   - Replace package.json licenses array with single license key and `"BSD-3-Clause"` value
   - Update code style to stop putting functions on single line (new lab will error on that lint warning)
* An extra challenge, after doing the above, refactor hapi-auth-basic registration code: 
   * Refactor the application to load hapi-auth-basic plugin using glue's manifest file.  
   * Remove hapi-auth-basic plugin registration code from the private.js file.
   * private.js plugins' functionality will not change.  We are just moving where the 
     hapi-auth-basic plugin is registered.  
   * Configure Glue to load hapi-auth-basic plugin and make a file dedicated to register the hapi-auth-basic strategy.
   Glue will reference this file in the manifest file to load the plugin. 
   * While making the assignment, there was discussion about why not to make this change. See: [The Discussion](https://github.com/hapijs/university/issues/132) for details. 
   But, I encourage everyone to try it.  Doing this exercise will help you get to know Glue and hapijs' auth plugin design better ;-)
   If you get stuck here, we will work together to make it work! 

#### What is coming next?
* adding static assets like css, images, js files.
* validation with joi
* sessions and authentication with hapi-auth-cookie
* See "What we are going to build?" section in the README https://github.com/hapijs/university  for the big picture plan.
* If you have suggestions for issues to study please make them!
Cheers!

### PR DESCRIPTION
**Pull request by FennNaten**
closes #136 
- server plugins registered with glue
- added home plugin, registering home route which uses a view
- auth code moved in its own plugin
- server.dependency used to prevent plugin registration code dependent on registration of other plugins from running before those plugins
- 100% test coverage
- cleanup: updated license field in package.json, removed makefile
- additional cleanup in package.json: version upgraded, repository location updated, package renamed hapi-university, added reference to handlebars

### CODE REVIEW

**Comment by FennNaten** [comment]
@zoe-1 You're right, I used it to test the prePlugins and forgot to remove it on cleanup

**Comment by zoe-1** [comment]
@FennNaten  Your PR is great!!
Your participation in the assignment really improved the quality of it. 
This work will help other developers using hapi avoid the gotchas you mentioned when trying to use Glue.  Using your PR and our discussions related to Glue, the aqua project, and the assignment,  we should improve the Glue documentation (For example, write some sample code and give explanations of core gotcha issues).  Hopefully, @hueniverse feels the same.     

Great job :-)

* If I was going to change anything, I would put the manifest JSON object in it's own file.  
I think people new to Glue would like to see that.  The assignment did not require it but it is the 
direction we are heading in.
* For those of you that want to see a Glue prePlugin load dependencies example, see:
https://github.com/jedireza/aqua/issues/36<br/>
This example was also made by @FennNaten!

**Comment by hueniverse** [comment]
glue has a maintainer and you should work with them to get better documentations going.

**Comment by zoe-1** [comment]
OK will do.

**Comment by hussainanjar** [comment]
Indeed @FennNaten got to learn a lot about glue and ways dependencies can be managed with Hapi :smile:

**Comment by zoe-1** [comment]
@hueniverse As discussed above, made PR to glue project to improve Glue Documentation.
https://github.com/hapijs/glue/pull/23

**Pull request merged**
