### PR TITLE
- Completed assignment "Static Assets, Partials, and TLS" issue #144

### PR DESCRIPTION
**Pull request by luismatute**

### CODE REVIEW

**Comment by luismatute** [comment]
Done

**Comment by luismatute** [comment]
Weird, npm test threw that everything was alright... I'm new to testing, sorry for the mistakes. Hopefully it works as expected now :)

screen shot 2015-06-15 at 8 54 14 am

**Comment by zoe-1** [comment]
@luismatute Probably, need to upgrade lab.  
Then, this will be fixed. Sometimes lab gets upgraded and they make it more strict 
then, older versions pass while newer versions fail.  It's happened to me before. 
I just upgraded so had listing errors.

**Comment by AdriVanHoudt** [comment]
Mainly my bad haha sowry :D if I have time there will be an update this week even `break all the things!` :D

**Pull request closed without merging**
